CREATE TABLE KOPO_PARAM_HANJIWON(
    PARAM_NAME VARCHAR(100),
    PARAM_VALUE VARCHAR(100)
)

INSERT INTO KOPO_PARAM_HANJIWON
VALUES ('SRC_TABLE', 'kopo_bankdata');

INSERT INTO KOPO_PARAM_HANJIWON
VALUES ('SRC_CON', 'mysql+pymysql://kopo:kopo@192.168.110.111:3306/kopo'); 

INSERT INTO KOPO_PARAM_HANJIWON
VALUES ('DEST_TABLE', 'kopo_bankdata_hanjiwon'); 

INSERT INTO KOPO_PARAM_HANJIWON
VALUES ('DEST_CON', 'oracle+cx_oracle://kopo:kopo@192.168.110.112:1521/orcl'); 